{
 "title": "Round Robin",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Responder Request Count",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_of_requests{job=\"responder\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Duration - Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg_response_duration_millis{job=\"lb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "response_status{job=\"lb\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}